"""
app/coder.py

Phase 6 - Coder. Extended in Phase 10 to vary feature engineering and
hyperparameters across Ralph loop iterations, routing model selection
through tools.ml (single source of truth for model construction).

STAND-IN FOR AN LLM CALL.

In a full implementation, this module would send the plan (and, on
retries, the previous iteration's failure feedback) to an LLM with a
prompt like:

    "Given this analysis plan: {plan}, and dataset at '{dataset_path}',
     write a complete, runnable Python script that trains model
     '{model_name}' and prints a single line of JSON metrics to stdout.
     Previous attempt failed because: {previous_feedback}. Fix it."

and use the LLM's returned code verbatim (after a syntax check).

For Phase 0 MVP (no API key available), we instead deterministically
render a Python script from a small set of string templates driven by
the plan dict. Swap the body of generate_code() for an LLM call when an
API key is available -- the function signature should not need to
change.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tools.ml import hyperparameter_grid, pick_hyperparams  # noqa: E402
from tools.dataset import MAX_ONEHOT_COLUMNS  # noqa: E402


def _feedback_comment(iteration: int, previous_feedback: str | None) -> str:
    lines = [f"# Iteration {iteration} - generated by AI Data Science Agent"]
    if previous_feedback:
        safe = previous_feedback.replace("\n", " ").replace('"""', "'''")
        lines.append(f"# Previous iteration feedback (informational only): {safe}")
    return "\n".join(lines) + "\n\n"


def _feature_engineering_for_iteration(iteration: int) -> str:
    """Alternate between 'basic' (one-hot + median-fill, the original
    Phase 0 behavior) and 'pipeline' (tools.ml.build_preprocessing_pipeline
    with scaling + optional feature selection) as iterations progress.
    """
    return "basic" if iteration % 2 == 0 else "pipeline"


def _generate_supervised_code(
    dataset_path: str,
    plan: dict,
    iteration: int,
    previous_feedback: str | None,
    model_name: str | None = None,
    feature_engineering: str | None = None,
    hyperparams: dict | None = None,
    models_dir: str | None = None,
) -> str:
    task_type = plan["task_type"]
    target = plan["target"]
    candidate_models = plan["candidate_models"]
    plan_metric = plan.get("metric")
    if model_name is None:
        model_name = candidate_models[iteration % len(candidate_models)]
    if hyperparams is None:
        hyperparams = pick_hyperparams(model_name, iteration) if hyperparameter_grid(model_name) else {}
    if feature_engineering is None:
        feature_engineering = _feature_engineering_for_iteration(iteration)

    header = _feedback_comment(iteration, previous_feedback)
    project_root_repr = repr(str(PROJECT_ROOT))

    if task_type == "classification":
        default_metric = "f1"
        metrics_block = '''
accuracy = accuracy_score(y_test, preds)
precision = precision_score(y_test, preds, average="weighted", zero_division=0)
recall = recall_score(y_test, preds, average="weighted", zero_division=0)
f1 = f1_score(y_test, preds, average="weighted", zero_division=0)

metric_values = {
    "accuracy": accuracy,
    "precision": precision,
    "recall": recall,
    "f1": f1,
}
DEFAULT_METRIC = "''' + default_metric + '''"
if METRIC not in metric_values:
    raise ValueError(f"Metric '{METRIC}' is not valid for classification")
actual_metric = METRIC
score = metric_values[actual_metric]

result = {
    "model": MODEL_NAME,
    "metric": actual_metric,
    "score": float(score),
    "accuracy": float(accuracy),
    "precision": float(precision),
    "recall": float(recall),
    "f1": float(f1),
    "hyperparams": HYPERPARAMS,
    "feature_engineering": FEATURE_ENGINEERING,
    "model_path": MODEL_PATH,
    "n_features": N_FEATURES,
    "train_samples": TRAIN_SAMPLES,
    "test_samples": TEST_SAMPLES,
    "feature_names": FEATURE_NAMES,
}
print(json.dumps(result))
'''
        sklearn_metrics_import = "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score"
    else:
        default_metric = "rmse"
        metrics_block = '''
mse = mean_squared_error(y_test, preds)
rmse = mse ** 0.5
mae = mean_absolute_error(y_test, preds)
r2 = r2_score(y_test, preds)

metric_values = {
    "rmse": rmse,
    "mae": mae,
    "r2": r2,
}
DEFAULT_METRIC = "''' + default_metric + '''"
if METRIC not in metric_values:
    raise ValueError(f"Metric '{METRIC}' is not valid for regression")
actual_metric = METRIC
score = metric_values[actual_metric]

result = {
    "model": MODEL_NAME,
    "metric": actual_metric,
    "score": float(score),
    "rmse": float(rmse),
    "mae": float(mae),
    "r2": float(r2),
    "hyperparams": HYPERPARAMS,
    "feature_engineering": FEATURE_ENGINEERING,
    "model_path": MODEL_PATH,
    "n_features": N_FEATURES,
    "train_samples": TRAIN_SAMPLES,
    "test_samples": TEST_SAMPLES,
    "feature_names": FEATURE_NAMES,
}
print(json.dumps(result))
'''
        sklearn_metrics_import = "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score"

    model_save_block = '''
MODELS_DIR = ''' + repr(models_dir) + '''
if MODELS_DIR:
    Path(MODELS_DIR).mkdir(parents=True, exist_ok=True)
    MODEL_PATH = str(Path(MODELS_DIR) / f"iteration_{ITERATION}_{MODEL_NAME}.joblib")
    joblib.dump(model, MODEL_PATH)
else:
    MODEL_PATH = None
'''

    sample_info_block = '''
FEATURE_NAMES = list(X.columns)
N_FEATURES = len(FEATURE_NAMES)
TRAIN_SAMPLES = int(X_train.shape[0])
TEST_SAMPLES = int(X_test.shape[0])
'''

    dropped_cols = plan.get("dropped_high_cardinality_columns") or []
    # Columns the profiler name-heuristically flagged as likely target
    # leakage (app/planner.py's leakage_dropped_columns) -- dropped here,
    # unconditionally, for every feature_engineering mode, the same way
    # high-cardinality columns already are. A profiler that warns "possible
    # leakage" but a generated script that still trains on the flagged
    # column would be a contradiction, not a warning.
    leakage_cols = plan.get("leakage_dropped_columns") or []
    drop_block = f'''
DROPPED_HIGH_CARDINALITY_COLUMNS = {dropped_cols!r}
DROPPED_LEAKAGE_COLUMNS = {leakage_cols!r}
X = X.drop(columns=[c for c in DROPPED_HIGH_CARDINALITY_COLUMNS + DROPPED_LEAKAGE_COLUMNS if c in X.columns])
'''

    low_card_cols = plan.get("low_cardinality_columns") or []
    medium_card_cols = plan.get("medium_cardinality_columns") or []

    if feature_engineering == "safe_categorical":
        feature_block = drop_block + f'''
LOW_CARDINALITY_COLUMNS = {low_card_cols!r}
MEDIUM_CARDINALITY_COLUMNS = {medium_card_cols!r}

for col in MEDIUM_CARDINALITY_COLUMNS:
    if col in X.columns:
        X[col] = X[col].map(X[col].value_counts()).fillna(0)

low_card_present = [c for c in LOW_CARDINALITY_COLUMNS if c in X.columns]
X = pd.get_dummies(X, columns=low_card_present, drop_first=True)
if X.shape[1] > MAX_ONEHOT_COLUMNS:
    raise RuntimeError(
        f"one-hot encoding produced {{X.shape[1]}} columns from {{X.shape[0]}} rows, "
        f"exceeding the safety cap of {{MAX_ONEHOT_COLUMNS}}; likely a high-cardinality "
        "column was not dropped"
    )
numeric_cols = X.select_dtypes(include="number").columns
X[numeric_cols] = X[numeric_cols].fillna(X[numeric_cols].median())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
''' + sample_info_block + '''
model = get_model(MODEL_NAME, TASK_TYPE, HYPERPARAMS)
model.fit(X_train, y_train)
preds = model.predict(X_test)
''' + model_save_block
    elif feature_engineering == "basic":
        feature_block = drop_block + '''
X = pd.get_dummies(X, drop_first=True)
if X.shape[1] > MAX_ONEHOT_COLUMNS:
    raise RuntimeError(
        f"one-hot encoding produced {X.shape[1]} columns from {X.shape[0]} rows, "
        f"exceeding the safety cap of {MAX_ONEHOT_COLUMNS}; likely a high-cardinality "
        "column was not dropped"
    )
numeric_cols = X.select_dtypes(include="number").columns
X[numeric_cols] = X[numeric_cols].fillna(X[numeric_cols].median())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
''' + sample_info_block + '''
model = get_model(MODEL_NAME, TASK_TYPE, HYPERPARAMS)
model.fit(X_train, y_train)
preds = model.predict(X_test)
''' + model_save_block
    else:
        feature_block = drop_block + '''
numeric_cols = X.select_dtypes(include="number").columns.tolist()
categorical_cols = X.select_dtypes(exclude="number").columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
''' + sample_info_block + '''
n_features = len(numeric_cols) + len(categorical_cols)
k = min(10, n_features) if n_features > 10 else None

preprocessor = build_preprocessing_pipeline(
    numeric_cols, categorical_cols, scale_numeric=True, feature_selection_k=k
)
_ohe_check = preprocessor.fit_transform(X_train)
_ohe_ncols = _ohe_check.shape[1]
if _ohe_ncols > MAX_ONEHOT_COLUMNS:
    raise RuntimeError(
        f"one-hot encoding produced {_ohe_ncols} columns from {X_train.shape[0]} rows, "
        f"exceeding the safety cap of {MAX_ONEHOT_COLUMNS}; likely a high-cardinality "
        "column was not dropped"
    )
model_step = get_model(MODEL_NAME, TASK_TYPE, HYPERPARAMS)
model = Pipeline([("preprocess", preprocessor), ("model", model_step)])
model.fit(X_train, y_train)
preds = model.predict(X_test)
''' + model_save_block

    if feature_engineering == "pipeline":
        ml_import = "from sklearn.pipeline import Pipeline\nfrom tools.ml import get_model, build_preprocessing_pipeline"
    else:
        ml_import = "from tools.ml import get_model"

    code = f'''{header}import json
import sys
import joblib
import pandas as pd
from pathlib import Path

sys.path.insert(0, {project_root_repr})

from sklearn.model_selection import train_test_split
{sklearn_metrics_import}
{ml_import}

DATASET_PATH = {dataset_path!r}
TARGET = {target!r}
MODEL_NAME = {model_name!r}
TASK_TYPE = {task_type!r}
HYPERPARAMS = {hyperparams!r}
FEATURE_ENGINEERING = {feature_engineering!r}
METRIC = {plan_metric!r}
ITERATION = {iteration!r}
MAX_ONEHOT_COLUMNS = {MAX_ONEHOT_COLUMNS!r}

df = pd.read_csv(DATASET_PATH)
df = df.dropna(subset=[TARGET])

y = df[TARGET]
X = df.drop(columns=[TARGET])
{feature_block}{metrics_block}'''
    return code


def _generate_eda_code(dataset_path: str, plan: dict, iteration: int, previous_feedback: str | None) -> str:
    header = _feedback_comment(iteration, previous_feedback)
    code = f'''{header}import json
import pandas as pd

DATASET_PATH = {dataset_path!r}

df = pd.read_csv(DATASET_PATH)

total_cells = df.shape[0] * df.shape[1]
missing_cells = int(df.isnull().sum().sum())
completeness = 1.0 - (missing_cells / total_cells) if total_cells else 0.0

result = {{
    "model": "eda",
    "metric": "completeness",
    "score": float(completeness),
    "shape": [int(df.shape[0]), int(df.shape[1])],
    "missing_cells": missing_cells,
    "hyperparams": {{}},
    "feature_engineering": "none",
}}
print(json.dumps(result))
'''
    return code


def generate_code(
    dataset_path: str,
    plan: dict,
    iteration: int,
    previous_feedback: str | None = None,
    model_name: str | None = None,
    feature_engineering: str | None = None,
    hyperparams: dict | None = None,
    models_dir: str | None = None,
) -> str:
    """Generate a complete, runnable Python script for this plan/iteration.

    `model_name`, `feature_engineering`, and `hyperparams` are optional
    explicit overrides (used by app.ralph to walk a deterministic search
    space). When omitted, they're derived from `iteration` as before
    (backward compatible with existing direct callers/tests).

    # TODO: replace with an LLM call using this prompt:
    #   "Given this analysis plan: {{plan}}, dataset at '{{dataset_path}}',
    #    and iteration {{iteration}}, write a complete Python script that
    #    trains the next candidate model and prints one line of JSON
    #    metrics to stdout. Previous feedback: '{{previous_feedback}}'."
    """
    task_type = plan.get("task_type")
    if task_type in ("classification", "regression"):
        return _generate_supervised_code(
            dataset_path,
            plan,
            iteration,
            previous_feedback,
            model_name=model_name,
            feature_engineering=feature_engineering,
            hyperparams=hyperparams,
            models_dir=models_dir,
        )
    return _generate_eda_code(dataset_path, plan, iteration, previous_feedback)
