"""
app/coder.py

Phase 6 - Coder. Extended in Phase 10 to vary feature engineering and
hyperparameters across Ralph loop iterations, routing model selection
through tools.ml (single source of truth for model construction).

STAND-IN FOR AN LLM CALL.

In a full implementation, this module would send the plan (and, on
retries, the previous iteration's failure feedback) to an LLM with a
prompt like:

    "Given this analysis plan: {plan}, and dataset at '{dataset_path}',
     write a complete, runnable Python script that trains model
     '{model_name}' and prints a single line of JSON metrics to stdout.
     Previous attempt failed because: {previous_feedback}. Fix it."

and use the LLM's returned code verbatim (after a syntax check).

For Phase 0 MVP (no API key available), we instead deterministically
render a Python script from a small set of string templates driven by
the plan dict. Swap the body of generate_code() for an LLM call when an
API key is available -- the function signature should not need to
change.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tools.ml import hyperparameter_grid, pick_hyperparams  # noqa: E402
from tools.dataset import MAX_ONEHOT_COLUMNS  # noqa: E402


def _feedback_comment(iteration: int, previous_feedback: str | None) -> str:
    lines = [f"# Iteration {iteration} - generated by AI Data Science Agent"]
    if previous_feedback:
        safe = previous_feedback.replace("\n", " ").replace('"""', "'''")
        lines.append(f"# Previous iteration feedback (informational only): {safe}")
    return "\n".join(lines) + "\n\n"


def _feature_engineering_for_iteration(iteration: int) -> str:
    """Alternate between 'basic' (one-hot + median-fill, the original
    Phase 0 behavior) and 'pipeline' (tools.ml.build_preprocessing_pipeline
    with scaling + optional feature selection) as iterations progress.
    """
    return "basic" if iteration % 2 == 0 else "pipeline"


def _generate_supervised_code(
    dataset_path: str,
    plan: dict,
    iteration: int,
    previous_feedback: str | None,
    model_name: str | None = None,
    feature_engineering: str | None = None,
    hyperparams: dict | None = None,
    models_dir: str | None = None,
) -> str:
    task_type = plan["task_type"]
    target = plan["target"]
    candidate_models = plan["candidate_models"]
    plan_metric = plan.get("metric")
    if model_name is None:
        model_name = candidate_models[iteration % len(candidate_models)]
    if hyperparams is None:
        hyperparams = pick_hyperparams(model_name, iteration) if hyperparameter_grid(model_name) else {}
    if feature_engineering is None:
        feature_engineering = _feature_engineering_for_iteration(iteration)

    header = _feedback_comment(iteration, previous_feedback)
    project_root_repr = repr(str(PROJECT_ROOT))

    if task_type == "classification":
        default_metric = "f1"
        metrics_block = '''
accuracy = accuracy_score(y_validation, preds)
precision = precision_score(y_validation, preds, average="weighted", zero_division=0)
recall = recall_score(y_validation, preds, average="weighted", zero_division=0)
f1 = f1_score(y_validation, preds, average="weighted", zero_division=0)

metric_values = {
    "accuracy": accuracy,
    "precision": precision,
    "recall": recall,
    "f1": f1,
}
DEFAULT_METRIC = "''' + default_metric + '''"
if METRIC not in metric_values:
    raise ValueError(f"Metric '{METRIC}' is not valid for classification")
actual_metric = METRIC
score = metric_values[actual_metric]

result = {
    "model": MODEL_NAME,
    "metric": actual_metric,
    "score": float(score),
    "accuracy": float(accuracy),
    "precision": float(precision),
    "recall": float(recall),
    "f1": float(f1),
    "hyperparams": HYPERPARAMS,
    "feature_engineering": FEATURE_ENGINEERING,
    "model_path": MODEL_PATH,
    "n_features": N_FEATURES,
    "train_samples": TRAIN_SAMPLES,
    "test_samples": TEST_SAMPLES,
    "feature_names": FEATURE_NAMES,
    "validation_method": "out_of_fold",
    "cv_folds": cv.n_splits,
}
print(json.dumps(result))
'''
        sklearn_metrics_import = "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score"
    else:
        default_metric = "rmse"
        metrics_block = '''
mse = mean_squared_error(y_validation, preds)
rmse = mse ** 0.5
mae = mean_absolute_error(y_validation, preds)
r2 = r2_score(y_validation, preds)

metric_values = {
    "rmse": rmse,
    "mae": mae,
    "r2": r2,
}
DEFAULT_METRIC = "''' + default_metric + '''"
if METRIC not in metric_values:
    raise ValueError(f"Metric '{METRIC}' is not valid for regression")
actual_metric = METRIC
score = metric_values[actual_metric]

result = {
    "model": MODEL_NAME,
    "metric": actual_metric,
    "score": float(score),
    "rmse": float(rmse),
    "mae": float(mae),
    "r2": float(r2),
    "hyperparams": HYPERPARAMS,
    "feature_engineering": FEATURE_ENGINEERING,
    "model_path": MODEL_PATH,
    "n_features": N_FEATURES,
    "train_samples": TRAIN_SAMPLES,
    "test_samples": TEST_SAMPLES,
    "feature_names": FEATURE_NAMES,
    "validation_method": "out_of_fold",
    "cv_folds": cv.n_splits,
}
print(json.dumps(result))
'''
        sklearn_metrics_import = "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score"

    model_save_block = '''
MODELS_DIR = os.environ.get("AGENT_MODELS_DIR", ''' + repr(models_dir) + ''')
if MODELS_DIR:
    Path(MODELS_DIR).mkdir(parents=True, exist_ok=True)
    MODEL_PATH = str(Path(MODELS_DIR) / f"iteration_{ITERATION}_{MODEL_NAME}.joblib")
    joblib.dump(model, MODEL_PATH)
else:
    MODEL_PATH = None
'''

    dropped_cols = plan.get("dropped_high_cardinality_columns") or []
    leakage_cols = plan.get("leakage_dropped_columns") or []
    medium_card_cols = plan.get("medium_cardinality_columns") or []
    feature_block = f'''
DROPPED_HIGH_CARDINALITY_COLUMNS = {dropped_cols!r}
DROPPED_LEAKAGE_COLUMNS = {leakage_cols!r}
MEDIUM_CARDINALITY_COLUMNS = {medium_card_cols!r}
X = X.drop(columns=[c for c in DROPPED_HIGH_CARDINALITY_COLUMNS + DROPPED_LEAKAGE_COLUMNS if c in X.columns])

# Reserve the final holdout before fitting any preprocessing or model.
X_train, X_holdout, y_train, y_holdout = split_development_holdout(X, y, TASK_TYPE)
numeric_cols = X_train.select_dtypes(include="number").columns.tolist()
categorical_cols = X_train.select_dtypes(exclude="number").columns.tolist()
frequency_cols = [c for c in categorical_cols if c in MEDIUM_CARDINALITY_COLUMNS] if FEATURE_ENGINEERING == "safe_categorical" else []
categorical_cols = [c for c in categorical_cols if c not in frequency_cols]
k = min(10, X_train.shape[1]) if FEATURE_ENGINEERING == "pipeline" and X_train.shape[1] > 10 else None
preprocessor = build_preprocessing_pipeline(
    numeric_cols, categorical_cols, scale_numeric=FEATURE_ENGINEERING == "pipeline",
    feature_selection_k=k, task_type=TASK_TYPE, frequency_cols=frequency_cols,
)
model = Pipeline([("preprocess", preprocessor), ("model", get_model(MODEL_NAME, TASK_TYPE, HYPERPARAMS))])
cv = validation_folds(y_train, TASK_TYPE)
# cross_val_predict clones the entire pipeline: encoders, imputation and
# supervised feature selection see only each fold's training partition.
preds = cross_val_predict(model, X_train, y_train, cv=cv)
y_validation = y_train
model.fit(X_train, y_train)
FEATURE_NAMES = model.named_steps["preprocess"].get_feature_names_out().tolist()
N_FEATURES = len(FEATURE_NAMES)
TRAIN_SAMPLES = len(X_train)
TEST_SAMPLES = len(X_holdout)
''' + model_save_block
    ml_import = "from sklearn.pipeline import Pipeline\nfrom tools.ml import get_model, build_preprocessing_pipeline"

    code = f'''{header}import json
import os
import sys
import joblib
import pandas as pd
from pathlib import Path

sys.path.insert(0, os.environ.get("AGENT_PROJECT_ROOT", {project_root_repr}))

from sklearn.model_selection import cross_val_predict
from tools.validation import split_development_holdout, validation_folds
{sklearn_metrics_import}
{ml_import}

DATASET_PATH = os.environ.get("AGENT_DATASET_PATH", {dataset_path!r})
TARGET = {target!r}
MODEL_NAME = {model_name!r}
TASK_TYPE = {task_type!r}
HYPERPARAMS = {hyperparams!r}
FEATURE_ENGINEERING = {feature_engineering!r}
METRIC = {plan_metric!r}
ITERATION = {iteration!r}
MAX_ONEHOT_COLUMNS = {MAX_ONEHOT_COLUMNS!r}

df = pd.read_csv(DATASET_PATH)
df = df.dropna(subset=[TARGET])

y = df[TARGET]
X = df.drop(columns=[TARGET])
{feature_block}{metrics_block}'''
    return code


def _generate_eda_code(dataset_path: str, plan: dict, iteration: int, previous_feedback: str | None) -> str:
    header = _feedback_comment(iteration, previous_feedback)
    code = f'''{header}import json
import os
import pandas as pd

DATASET_PATH = os.environ.get("AGENT_DATASET_PATH", {dataset_path!r})

df = pd.read_csv(DATASET_PATH)

total_cells = df.shape[0] * df.shape[1]
missing_cells = int(df.isnull().sum().sum())
completeness = 1.0 - (missing_cells / total_cells) if total_cells else 0.0

result = {{
    "model": "eda",
    "metric": "completeness",
    "score": float(completeness),
    "shape": [int(df.shape[0]), int(df.shape[1])],
    "missing_cells": missing_cells,
    "hyperparams": {{}},
    "feature_engineering": "none",
}}
print(json.dumps(result))
'''
    return code


def generate_code(
    dataset_path: str,
    plan: dict,
    iteration: int,
    previous_feedback: str | None = None,
    model_name: str | None = None,
    feature_engineering: str | None = None,
    hyperparams: dict | None = None,
    models_dir: str | None = None,
) -> str:
    """Generate a complete, runnable Python script for this plan/iteration.

    `model_name`, `feature_engineering`, and `hyperparams` are optional
    explicit overrides (used by app.ralph to walk a deterministic search
    space). When omitted, they're derived from `iteration` as before
    (backward compatible with existing direct callers/tests).

    # TODO: replace with an LLM call using this prompt:
    #   "Given this analysis plan: {{plan}}, dataset at '{{dataset_path}}',
    #    and iteration {{iteration}}, write a complete Python script that
    #    trains the next candidate model and prints one line of JSON
    #    metrics to stdout. Previous feedback: '{{previous_feedback}}'."
    """
    task_type = plan.get("task_type")
    if task_type in ("classification", "regression"):
        return _generate_supervised_code(
            dataset_path,
            plan,
            iteration,
            previous_feedback,
            model_name=model_name,
            feature_engineering=feature_engineering,
            hyperparams=hyperparams,
            models_dir=models_dir,
        )
    return _generate_eda_code(dataset_path, plan, iteration, previous_feedback)
